services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8500:8500/udp"
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    container_name: api-gateway
    environment:
      - ASPNETCORE_URLS=http://+:8090
      - Consul__Host=consul
      - Consul__Port=8500
    ports:
      - "8090:8090"
    depends_on:
      - consul
      
  auth-service:
    build:
      context: .
      dockerfile: src/Services/Auth/Dockerfile
    container_name: auth-service
    environment:
      - ASPNETCORE_URLS=http://+:5235
      - Consul__Host=consul
      - Consul__Port=8500
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/restApi.db
    ports:
      - "5235:5235"
    volumes:
      - ./src/Services/Auth/data:/app/data
    depends_on:
      - consul